version: "3.8"

services:
  db:
    image: postgres:12
    container_name: dtb_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
    env_file:
      - ./.env
    ports:
      - 5434:5432
  redis:
    image: redis:alpine
    container_name: dtb_redis
  web:
    build: .
    container_name: dtb_django
    command: bash -c "python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    environment:
      - DJANGO_DEBUG='False'
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    entrypoint: /entrypoint.sh
  bot:
    build: .
    container_name: dtb_bot
    command: python run_pooling.py
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - web
  celery:
    build: .
    container_name: dtb_celery
    command: celery -A dtb worker --loglevel=INFO
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
  celery-beat:
    build: .
    container_name: dtb_beat
    command: celery -A dtb beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
      - web

volumes:
  postgres_data:
