# Generated by Django 3.2 on 2022-05-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_experience_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='standing',
            field=models.CharField(choices=[('1', 'Меньше 6 мес'), ('2', 'От 6 мес до 1 года'), ('3', 'От 1 года до 3 лет'), ('4', 'Больше 5 лет')], max_length=300, null=True),
        ),
    ]
