# Generated by Django 3.2 on 2022-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_alter_experience_standing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Новые'), ('1', 'В работе'), ('2', 'На собеседовании'), ('3', 'В архиве')], max_length=300, null=True, verbose_name='Статус анкеты'),
        ),
    ]
