# Generated by Django 3.2 on 2022-05-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Новая'), ('1', 'В работе'), ('2', 'На собеседовании'), ('3', 'В архиве'), ('9', 'Незавершенная')], default='9', max_length=300, null=True, verbose_name='Статус анкеты'),
        ),
    ]
