# Generated by Django 3.2 on 2022-05-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_profile_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['status'], 'verbose_name': 'Профайл', 'verbose_name_plural': 'Профайлы'},
        ),
    ]
