# Generated by Django 3.2 on 2022-06-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevalues',
            name='is_base',
            field=models.BooleanField(default=False, verbose_name='Выводится всем'),
        ),
        migrations.AlterField(
            model_name='employeevalues',
            name='title',
            field=models.TextField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='Нет описания', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
