# Generated by Django 3.2 on 2022-06-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_auto_20220605_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('0', 'Новая'), ('1', 'В работе'), ('2', 'На собеседовании'), ('3', 'В архиве'), ('9', 'Незавершенная')], max_length=300, null=True, verbose_name='Статус анкеты')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.profile')),
            ],
            options={
                'verbose_name': 'История статуса профайла',
                'verbose_name_plural': 'История статусов профайла',
            },
        ),
    ]
