# Generated by Django 3.2 on 2022-06-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_alter_profilestatushistory_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestatushistory',
            options={'verbose_name': 'История статуса профайла', 'verbose_name_plural': 'Истории статусов профайла'},
        ),
        migrations.AlterField(
            model_name='profilestatushistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.profile', verbose_name='Профайл'),
        ),
        migrations.AlterField(
            model_name='profilestatushistory',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Новая'), ('1', 'В работе'), ('2', 'На собеседовании'), ('3', 'В архиве'), ('9', 'Незавершенная')], default='9', max_length=300, null=True, verbose_name='Статус анкеты'),
        ),
    ]
