# Generated by Django 3.2 on 2022-06-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_auto_20220606_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestatushistory',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Новая'), ('1', 'В работе'), ('2', 'На собеседовании'), ('3', 'В архиве'), ('9', 'Незавершенная')], max_length=300, null=True, verbose_name='Статус анкеты'),
        ),
    ]
