# Generated by Django 3.2 on 2022-06-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_alter_profilestatushistory_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestatushistory',
            options={'ordering': ['status'], 'verbose_name': 'История статуса профайла', 'verbose_name_plural': 'Истории статусов профайла'},
        ),
    ]
