# Generated by Django 3.2 on 2022-06-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_alter_profilestatushistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestatushistory',
            options={'ordering': ['date'], 'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
        migrations.AlterField(
            model_name='profilestatushistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilestatushistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profilestatushistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.profile'),
        ),
        migrations.AlterField(
            model_name='profilestatushistory',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Новая'), ('1', 'В работе'), ('2', 'На собеседовании'), ('3', 'В архиве'), ('9', 'Незавершенная')], max_length=300, null=True),
        ),
    ]
