# Generated by Django 3.2 on 2022-06-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0015_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestatushistory',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='profilestatushistory',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='profilestatushistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='profilestatushistory',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Новая'), ('1', 'В работе'), ('2', 'На собеседовании'), ('3', 'В архиве'), ('9', 'Незавершенная')], max_length=300, null=True, verbose_name='Статус анкеты'),
        ),
    ]
