# Generated by Django 3.2 on 2022-06-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0016_auto_20220606_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestatushistory',
            options={'ordering': ['profile', 'date'], 'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
        migrations.AlterField(
            model_name='profilestatushistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.profile', verbose_name='Профайл'),
        ),
    ]
