# Generated by Django 3.2 on 2022-06-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0017_auto_20220607_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
    ]
