# Generated by Django 3.2 on 2022-06-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0019_auto_20220607_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание этапа')),
                ('next_statuses', models.ManyToManyField(blank=True, null=True, related_name='_tgbot_profilestatuses_next_statuses_+', to='tgbot.ProfileStatuses', verbose_name='Следующие этапы')),
            ],
        ),
    ]
