# Generated by Django 3.2 on 2022-06-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0020_profilestatuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestatuses',
            options={'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
        migrations.AddField(
            model_name='profilestatuses',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='profilestatuses',
            name='next_statuses',
            field=models.ManyToManyField(blank=True, null=True, to='tgbot.ProfileStatuses', verbose_name='Следующие этапы'),
        ),
    ]
