# Generated by Django 3.2 on 2022-06-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0021_auto_20220607_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot.profilestatuses', verbose_name='Тру статус'),
        ),
        migrations.AddField(
            model_name='profilestatushistory',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot.profilestatuses', verbose_name='Тру статус'),
        ),
    ]
