# Generated by Django 3.2 on 2022-06-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0022_auto_20220607_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestatuses',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название этапа'),
        ),
    ]
