# Generated by Django 3.2 on 2022-09-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0024_profilestatushistory_performer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['stage'], 'verbose_name': 'Профайл', 'verbose_name_plural': 'Профайлы'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profilestatushistory',
            name='status',
        ),
        migrations.AlterField(
            model_name='profile',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot.profilestatuses', verbose_name='Этап статус'),
        ),
    ]
