name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - id: deploy
      name: Deploy to dokku
      uses: none
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: 'none.com'
          app-name: 'dtb'
          git-push-flags: '--force'
